---
deployment:
  tasks:
    - export DEPLOYPATH=/home/y79k53kuxblh/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.css $DEPLOYPATH
    - /bin/cp logo-Summit-High.png $DEPLOYPATH
    - /bin/cp 20180113_104100.jpg $DEPLOYPATH